export const items = [
  {
    id: 1,
    image: "https://img.freepik.com/free-photo/seafood-pizza_74190-5944.jpg?w=996&t=st=1693062328~exp=1693062928~hmac=53fd9ad496580db41c6ca8066510cd89c6b0a0389de8bb6b875a78a1eda09cb5",
    name: "Onion Pizza",
    price: 150,
    description: "A delicious pizza topped ",
    category: "Pakistani",
    rating: 4.5,
  },
  {
    id: 2,
    image: "https://w7.pngwing.com/pngs/339/55/png-transparent-pizza-margherita-italian-cuisine-hot-dog-pizza-cheese-pizza-thumbnail.png",
    name: "Margherita Pizza",
    price: 130,
    description: "A classic Italian pizza ",
    category: "Pakistani",
    rating: 4.2,
  },
  {
    id: 3,
    image: "https://w7.pngwing.com/pngs/21/55/png-transparent-pepperoni-pizza-margarita-pizza-margherita-italian-cuisine-tomato-pizza-food-cheese-recipe-thumbnail.png",
    name: "Pepperoni Pizza",
    price: 160,
    description: "Indulge in the savory delight of this Pepperoni Pizza.",
    category: "Pakistani",
    rating: 4.6,
  },
  {
    id: 4,
    image: "https://w7.pngwing.com/pngs/569/109/png-transparent-pizza-with-vegetables-and-mushroom-toppings-sicilian-pizza-california-style-pizza-pizza-margherita-vegetarian-cuisine-pizza-food-recipe-gourmet-thumbnail.png",
    name: "Mushroom and Spinach Pizza",
    price: 140,
    description: "Experience the earthy flavors of mushrooms",
    category: "Pakistani",
    rating: 4.2,
  },
  {
    id: 5,
    image: "https://w7.pngwing.com/pngs/843/171/png-transparent-pizza-73-restaurant-catupiry-chicken-as-food-pizza-baked-goods-food-recipe-thumbnail.png",
    name: "BBQ Chicken Pizza",
    price: 170,
    description: "Savor the smoky goodness of this BBQ Chicken Pizza.",
    category: "Pakistani",
    rating: 4.8,
  },
  {
    id: 6,
    image: "https://w7.pngwing.com/pngs/133/54/png-transparent-pancakes-served-on-plate-banana-pancakes-scrambled-eggs-breakfast-ihop-pancake-food-recipe-eating-thumbnail.png",
    name: "Classic Pancakes",
    price: 80,
    description: "Start your ",
    category: "Chinese",
    rating: 4.5,
  },
  {
    id: 7,
    image: "https://w7.pngwing.com/pngs/645/475/png-transparent-croissant-bread-croissant-muffin-brunch-bacon-egg-and-cheese-sandwich-bread-croissants-baked-goods-food-baking-thumbnail.png",
    name: "Egg and Bacon Croissant",
    price: 110,
    description: "Indulge in a buttery croissant ",
    category: "Chinese",
    rating: 4.2,
  },
  {
    id: 8,
    image: "https://w7.pngwing.com/pngs/683/103/png-transparent-frozen-yogurt-parfait-Chinese-yoghurt-fruit-salad-yogurt-frutti-di-bosco-food-Chinese-thumbnail.png",
    name: "Greek Yogurt Parfait",
    price: 95,
    description: "Enjoy a healthy",
    category: "Chinese",
    rating: 4.1,
  },
  {
    id: 9,
    image: "https://w7.pngwing.com/pngs/400/603/png-transparent-toast-tostytosty-la-tosteria-menu-food-dish-avocado-toast-food-toast-avocado-toast-thumbnail.png",
    name: "Avocado Toast",
    price: 120,
    description: "Savor the creaminess of mashed",
    category: "Fast Food",
    rating: 4.6,
  },
  {
    id: 10,
    image: "https://w7.pngwing.com/pngs/20/725/png-transparent-grain-bowl-Fast Food-cereal-muesli-corn-flakes-bowl-granola-food-Fast Food-recipe-thumbnail.png",
    name: "Fruit and Nut Oatmeal",
    price: 85,
    description: "Warm up with a bowl",
    category: "Fast Food",
    rating: 4.5,
  },
  {
    id: 11,
    image: "https://w7.pngwing.com/pngs/875/111/png-transparent-north-fish-seafood-dish-smoked-salmon-restaurant-grilled-fish-hd-soup-food-seafood-thumbnail.png",
    name: "Grilled Salmon",
    price: 190,
    description: "Delight in a perfectly .",
    category: "Continental",
    rating: 4.5,
  },


];
export default items;

